### ISSUE TITLE
Windows 64-bit Chrome can't reset calc

### ISSUE THREAD

**Issue by RuralAnemone** [lights0123/n-link#8] opened 2021-03-23 17:41 UTC
[n-link.lights0123.com-1616521175798.log](https://github.com/lights0123/n-link/files/6191715/n-link.lights0123.com-1616521175798.log)
I finally got logs to show up

**Comment by lights0123** [comment] 2021-04-05 02:18
Yep, Chrome bug. Duplicate of #6

**Closed by lights0123** 2021-04-05 02:18 UTC
